### ISSUE TITLE
text=True no longer works

### ISSUE THREAD

**Issue by gpacix** [rsmith-nl/scripts#1]
I'm running Python 3.6, and got errors like this:
```
Traceback (most recent call last):
  File "/Users/george/gitdates.py", line 79, in <module>
    main()
  File "/Users/george/gitdates.py", line 29, in main
    exc = sp.run(exargs, stdout=sp.PIPE, stderr=sp.DEVNULL, text=True).stdout.split()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```
It seems like the Popen (and therefore the run) interface has changed in 3.7 to allow just "text=True", rather than 3.6 which requires a specific encoding . Here's a patch that works on 3.6, but I haven't tested it on 3.7 (or pre-3.6):

```
diff ~/gitdates.py~ ~/gitdates.py
29c29
<     exc = sp.run(exargs, text=True, stdout=sp.PIPE, stderr=sp.DEVNULL).stdout.split()
---
>     exc = sp.run(exargs, stdout=sp.PIPE, stderr=sp.DEVNULL, encoding='ascii').stdout.split()
66c66
<         b = sp.run(args, stdout=sp.PIPE, stderr=sp.DEVNULL, text=True, check=True).stdout
---
>         b = sp.run(args, stdout=sp.PIPE, stderr=sp.DEVNULL, check=True, encoding='ascii').stdout
```

**Comment by rsmith-nl** [comment]
The thing is that `encoding="ascii"` is bound to fail with e.g. unicode filenames. I'll change `text` to `universal_newlines`. That should work with 3.6.
